/**
 * The English dictionary isn't quite needed.
 * But it exists as an additional example and for unification of code.
 * However, if you want to create a new localization, use Russian dictionary for reference and additional comments.
 *
 * The dictionary was made form the Russian via automatic replacement of (".+")(:\s+)(".+") regular expression to $1$2$1
 */

export default {
    // language info
    englishName: "English",
    nativeName: "English",

    "Language": "Language", // not used now, but will be used in options afterwards

    // Translation: tooltips and notification
    // (to see the notification window, remove several phrases from any dictionary, except for the English one)
    "Add more":
        "Add more",
    "The translation isn't complete.":
        "The translation isn't complete.",
    "The following phrases are not translated:":
        "The following phrases are not translated:",
    "You can improve the translation here":
        "You can improve the translation here",

    // Initial screen
    "Click the #helpButton button to know more about the app":
        "Click the #helpButton button to know more about the app",
    "powered with":
        "powered with",
    "Drag & Drop a file here or click to choose manually":
        "Drag & Drop a file here or click to choose manually",
    "Paste a URL to a djvu file here":
        "Paste a URL to a djvu file here",
    "Open URL":
        "Open URL",
    // an alert shown when there is no link to open
    "Enter a valid URL to a djvu into the field":
        "Enter a valid URL to a djvu into the field",

    // Errors. To see an error notification try to open a not-djvu file.
    // To see a page error open manually a file from 'library/assets/czech_indirect/index.djvu
    // The very error messages are generated by the library and aren't translated now.
    "Error": "Error",
    "Error on page": "Error on page",
    "Error details": "Error details",

    // Options and its tooltips
    "Open all links with .djvu at the end via the viewer":
        "Open all links with .djvu at the end via the viewer",
    "All links to .djvu files will be opened by the viewer via a simple click on a link":
        "All links to .djvu files will be opened by the viewer via a simple click on a link",
    "Detect .djvu files by means of http headers":
        "Detect .djvu files by means of http headers",
    "Analyze headers of every new tab in order to process even links which do not end with the .djvu extension":
        "Analyze headers of every new tab in order to process even links which do not end with the .djvu extension",

    // Footer: status bar
    "Ready": "Ready",
    "Loading": "Loading",

    // Footer: buttons' tooltips
    "Show help window": "Show help window",
    "Switch full page mode": "Switch full page mode",

    // File Block tooltips
    "Choose a file": "Choose a file",
    "Close document": "Close document",
    "Save document": "Save document",
    "Save": "Save",
    "Open another .djvu file": "Open another .djvu file",

    // Help window
    "The application for viewing .djvu files in the browser.":
        "The application for viewing .djvu files in the browser.",
    "If something doesn't work properly, feel free to write about the problem at #email.":
        "If something doesn't work properly, feel free to write about the problem at #email.",
    "The official website is #website.":
        "The official website is #website.",
    "The source code is available on #link.":
        "The source code is available on #link.",
    "Hotkeys":
        "Hotkeys",
    "save the document":
        "save the document",
    "go to the previous page":
        "go to the previous page",
    "go to the next page":
        "go to the next page",
    "Controls":
        "Controls",
    "#expandIcon and #collapseIcon are to switch the viewer to the full page mode and back.":
        "#expandIcon and #collapseIcon are to switch the viewer to the full page mode and back.",
    "If you work with the browser extension, these buttons will cause no effect, since the viewer takes the whole page by default.":
        "If you work with the browser extension, these buttons will cause no effect, since the viewer takes the whole page by default.",

    // Toolbar tooltips
    "Continuous scroll view mode":
        "Continuous scroll view mode",
    "Single page view mode":
        "Single page view mode",
    "Text view mode":
        "Text view mode",
    "Click on the number to enter it manually":
        "Click on the number to enter it manually",
    "Rotate the page":
        "Rotate the page",
    "You also can scale the page via Ctrl+MouseWheel":
        "You also can scale the page via Ctrl+MouseWheel",
    "Text cursor mode":
        "Text cursor mode",
    "Grab cursor mode":
        "Grab cursor mode",

    // Contents
    "Contents": "Contents",
    "No contents provided": "No contents provided",

    // Text Block (shown in the text view mode)
    "No text on this page": "No text on this page",

    // Save dialog (shows when you save an indirect djvu)
    "You are trying to save an indirect (multi-file) document.":
        "You are trying to save an indirect (multi-file) document.",
    "What exactly do you want to do?":
        "What exactly do you want to do?",
    "Save only index file":
        "Save only index file",
    "Download, bundle and save the whole document as one file":
        "Download, bundle and save the whole document as one file",
    "Downloading and bundling the document":
        "Downloading and bundling the document",
    "The document has been downloaded and bundled into one file successfully":
        "The document has been downloaded and bundled into one file successfully",
};